<?php

/*
  http://projecteuler.net/problem=45

  Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

  Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
  Pentagonal	Pn=n(3n-1)/2	1, 5, 12, 22, 35, ...
  Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
  It can be verified that T(285) = P(165) = H(143) = 40755.

  Find the next triangle number that is also pentagonal and hexagonal.
 */

set_time_limit(0);

function triangle($broj) {
    for ($i = 1; $i <= $broj; $i++) {

        if ($broj == $i * ($i + 1) / 2) {
            return $i;
        }
    }
}

function pentagonal($broj) {
    for ($i = 1; $i <= $broj; $i++) {

        if ($broj == $i * (3 * $i - 1) / 2) {
            return $i;
        }
    }
}

function hexagonal($broj) {
    for ($i = 1; $i <= $broj; $i++) {

        if ($broj == $i * (2 * $i - 1)) {
            echo $broj . '<br/>';
        }
    }
}

$broj = 40755;

while (true) {
    if ($t = triangle($broj)) {

        if ($p = pentagonal($broj)) {
            hexagonal($broj);
            if ($broj > 40755) {
                break;
            }
        }
    }
    $broj++;
}
?>
